micronaut:
  application:
    name: audit-service
  server:
    port: 8766
  caches:
    discovery-client:
      enabled: false
  security:
    authentication: bearer
    token:
      roles-name: 'roles'
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: 'http://localhost:8180/auth/realms/MedLabMS/protocol/openid-connect/certs'
netty:
  default:
    allocator:
      max-order: 3
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
kafka:
  bootstrap:
    servers: localhost:29092
  consumer:
    group:
      id: audit-service
    key:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto:
      offset:
        reset: earliest
jpa:
  default:
    reactive: true
    entity-scan:
      packages:
        - 'com.medlabms.models.entities'
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:postgresql://localhost:5432/medlabms
          username: postgres
          password: postgres