spring:
  application:
    name: identity-service
  r2dbc:
    url: r2dbc:postgres://postgres@localhost:5432/medlabms
    username: postgres
    password: postgres
  #  rsocket:
#    server:
#      port: 8765
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/MedLabMS
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true