spring:
  application:
    name: identity-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      max:
        request:
          size: 1000
      linger:
        ms: 0
      spring:
        json:
          trusted:
            packages: '*'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/medlabms
#  r2dbc:
#    url: r2dbc:postgres://postgres@localhost:5432/medlabms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #  rsocket:
#    server:
#      port: 8765
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/MedLabMS
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        heartbeat:
          enabled: true
          ttl: 10s
#    discovery:
#      client:
#        simple:
#          instances:
#            your-application-name:
#              - uri: http://localhost:8761/eureka/
#      health-check-path: ${management.server.servlet.context-path}/actuator/health
#      health-check-interval: 15s
#      instance:
#        lease-renewal-interval-in-seconds: 10
server:
  port: 8764
  tomcat:
    relaxed-query-chars: '[,]'
AUDIT_PRODUCER_DTO_TOPIC:
  medlabms.audit