spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/medlabms
    user: postgres
    password: postgres
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/medlabms
    username: postgres
    password: postgres